export const SET_BALANCE = 'SET_BALANCE';
export const DEPOSIT_INTO_ACCOUNT = 'DEPOSIT_INTO_ACCOUNT';
export const WITHDRAW_FROM_ACCOUNT = 'WITHDRAW_FROM_ACCOUNT';
export const FETCH_BITCOIN = "FETCH_BITCOIN";
